version: '3'

services:
  archive-host:
    shm_size: "1gb"
    build:
      context: ../archive-host
    environment:
      - ARCHIVEHOST=10.1.0.2
      - CONTROLPORT=17000
      - EVENTSPORT=17001
    hostname: archive-host
    networks:
      default:
        ipv4_address: 10.1.0.2
  archive-client:
    shm_size: "1gb"
    build:
      context: ../archive-client
    environment:
      - ARCHIVEHOST=10.1.0.2
      - THISHOST=10.1.0.3
      - CONTROLPORT=17000
      - EVENTSPORT=17001
    hostname: archive-client
    networks:
      default:
        ipv4_address: 10.1.0.3
networks:
  default:
    driver: bridge
    ipam:
        config:
          - subnet: 10.1.0.0/24
